#!/usr/bin/env bash
compat="$PGE_COMPAT_DIR"
slug="GloriousEggroll/proton-ge-custom"
version="0.3.0"
tool="pge"

get_latest(){
    local url="https://api.github.com/repos/$slug/releases?per_page=1"
    curl -s "$url" > /tmp/pge
    < /tmp/pge jq -r '.[] .tag_name'
}
news(){
    local url="https://api.github.com/repos/$slug/releases?per_page=1"
    local id=$(curl -s "$url" | jq -r '.[] .id')
    local news_url="https://api.github.com/repos/$slug/releases/$id"
    local res=$(curl -s "$news_url")
    echo
    <<< $res jq -r '.tag_name'
    <<< $res jq -r '.body'
    echo
}
get_current(){
    ls -1 $compat | sort -V | grep GE-Proton | tail -n1
}
dl(){
    local tb="$(get_latest).tar.gz"
    local dl="https://github.com/$slug/releases/download/$latest/$tb"
    local size=$(< /tmp/pge jq '.[].assets[1].size')
    local avail=$(df -B1 $PGE_COMPAT_DIR --output=avail | awk 'END{print $1=$1}')
    if [[ $size > $avail ]]; then
        echo "Not enough space available on disk"
        exit 1
    fi
    wget $dl -O $compat/$tb &&
    tar xvf $compat/$tb -C $compat
    rm $compat/$tb
}
notify(){
    local current=$(get_current)
    local latest=$(get_latest)
    if [[ $current != $latest ]]; then
        echo "$latest"
        exit 1
    fi
    exit 0
}
info(){
    local current=$(get_current)
    local latest=$(get_latest)
    echo -e "Current:     $current"
    echo -e "Latest:      $latest"
    if [[ $current != $latest ]]; then
        while true; do
            read -p "Local version out of date. Fetch latest? [Y/n] " resp
            case $resp in
                ""|y|Y)
                    update &&
                    exit 0
                    ;;
                n|N)
                    exit 0
                    ;;
                *)
                    continue
                    ;;
            esac
        done
    fi
}
update(){
    local current=$(get_current)
    local latest=$(get_latest)
    if [[ $latest == $current ]]; then
        echo "Already up to date ($latest)"
    else
        dl
    fi
}
list(){
    ls -1 $compat | sort -V | grep GE
}
usage(){
    local pge="Proton-GE"

    declare -A usage
    local arrname="usage"
    usage["info"]="list $pge version info"
    usage["list"]="list installed $pge versions"
    usage["update"]="download latest $pge"
    usage["jump"]="jump to compat tool dir"
    usage["news"]="get latest release notes"
    usage["notify"]="returns 1 if upstream $pge is newer"
    usage["remove"]="remove compat tool by index"
    usage["-v"]="list tool version"

    local -n usage_arr="$arrname"
    longest=$(printf "%s\n" "${!usage_arr[@]}" | sort | tail -n1)
    wc=$(<<< "$longest" wc -m)
    offset=$((wc + 4))
    echo ""
    printf "\tUSAGE: %s <mode>\n" "$tool"
    echo ""
    for i in ${!usage_arr[@]}; do
        printf "\t%-${offset}s %s\n" "$i" "${usage_arr[$i]}"
    done | sort
    echo ""
}
jump(){
    cd "$compat"
    $SHELL
}
remove(){
    readarray -t vers < <(list)
    for ((i=0;i<${#vers[@]};i++)); do
        printf "%i  %s\n" $i "${vers[$i]}"
    done
    while true; do
        read -p "Remove index: " choice
        [[ -z $choice ]] && continue
        [[ ! $choice =~ ^[0-9]+$ ]] && continue
        [[ $choice -gt $((${#vers[@]}-1)) ]] && continue
        while true; do
            read -p "Remove '$compat/${vers[$choice]}'? [Y/n] " resp
            case $resp in
                ""|y|Y)
                    rm -rf "$compat/${vers[$choice]}"
                    echo "Removed ${vers[$choice]}"
                    exit 0
                    ;;
                n|N)
                    exit 0
                    ;;
                *)
                    continue
                    ;;
            esac
        done
        break
    done
}

version(){
    echo "PGE $version"
}

[[ -z $PGE_COMPAT_DIR ]] && { echo "PGE_COMPAT_DIR not set"; exit 1; }
[[ $# -lt 1 ]] && { usage; exit 1; }
[[ $1 == "-v" ]] && { version; exit 0; }

if [[ $(type -t $1) == function ]]; then
    $1
else
    usage
fi
